name: Elixir CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.3.4, 1.4.5, 1.5.3, 1.6.6, 1.7.4, 1.8.1]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: 22.2  # Adjust OTP version as needed
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
